-- ZeroPlay Supabase Auth schema.
-- Run this in the Supabase SQL editor or through your migration tool.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (
    char_length(username) between 3 and 30
    and username ~ '^[A-Za-z0-9_]+$'
  ),
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_username_lower_idx
  on public.profiles (lower(username));

alter table public.profiles enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_username text;
begin
  profile_username := nullif(new.raw_user_meta_data ->> 'username', '');

  if profile_username is null then
    profile_username := 'user_' || replace(left(new.id::text, 8), '-', '');
  end if;

  insert into public.profiles (id, username)
  values (new.id, profile_username)
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop policy if exists "Profiles are selectable by owner" on public.profiles;
create policy "Profiles are selectable by owner"
  on public.profiles
  for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
  on public.profiles
  for insert
  to authenticated
  with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles
  for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint favorites_user_team_unique unique (user_id, team_id)
);

create index if not exists favorites_user_id_idx
  on public.favorites (user_id);

create index if not exists favorites_team_id_idx
  on public.favorites (team_id);

alter table public.favorites enable row level security;

drop policy if exists "Favorites are selectable by owner" on public.favorites;
create policy "Favorites are selectable by owner"
  on public.favorites
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own favorites" on public.favorites;
create policy "Users can insert their own favorites"
  on public.favorites
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own favorites" on public.favorites;
create policy "Users can delete their own favorites"
  on public.favorites
  for delete
  to authenticated
  using (auth.uid() = user_id);

grant select, insert, update on public.profiles to authenticated;
grant select, insert, delete on public.favorites to authenticated;
