-- ZeroPlay team sync schema support.
-- Run once in Supabase before the first sync if the teams table does not
-- already have these columns and the name/league uniqueness guarantee.

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  league text not null,
  country text not null,
  updated_at timestamptz not null default now()
);

alter table public.teams
  add column if not exists country text;

alter table public.teams
  add column if not exists updated_at timestamptz not null default now();

update public.teams
set country = 'Unknown'
where country is null;

update public.teams
set updated_at = now()
where updated_at is null;

alter table public.teams
  alter column name set not null,
  alter column league set not null,
  alter column country set not null,
  alter column updated_at set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'teams_name_league_unique'
      and conrelid = 'public.teams'::regclass
  ) then
    alter table public.teams
      add constraint teams_name_league_unique unique (name, league);
  end if;
end $$;
